model: "LinearDQN"

env:
    env_name: "debug_test_env"
    overwrite_render: True
    record: False # IMPORTANT: must be set to false!
    max_val: 255.
    seed: 2025

output:
    output_path: &output_path "results/debug_test_env/LinearDQN/"
    model_output: !join_path [*output_path, "saved_weights/"]
    log_path: !join_path [*output_path, "log.txt"]
    plot_output: *output_path
    tensorboard: !join_path [*output_path, "tensorboard/"]

model_training:
    loss: "double_dqn"
    num_episodes_test: 20
    grad_clip: True
    clip_val: 10
    saving_freq: 5000
    log_freq: 50
    eval_freq: 1000
    soft_epsilon: 0
    compile: False
    compile_mode: "default"

hyper_params:
    nsteps_train: 10000
    batch_size: 32
    buffer_size: 1000
    target_update_freq: 500
    gamma: 0.99
    learning_freq: 4
    state_history: 2
    lr_begin: 0.005
    lr_end: 0.001
    lr_nsteps: 5000
    eps_begin: 1
    eps_end: 0.01
    eps_nsteps: 5000
    learning_start: 200
    eps: 1e-5
    alpha: 0.6
    beta_begin: 0.4
    beta_end: 1.0
    beta_nsteps: 10000
