# This config run the LinearDQN model on the ALE/Pong-v5 env, with the full training
# parameter set i.e. the configuration to be used for the final model
model: "LinearQN"

env:
    env_name: "ALE/Pong-v5"
    render_train: True
    render_test: True
    overwrite_render: True
    record: True
    max_val: 255.
    render_mode: "rgb_array"

output:
    output_path: &output_path "results/pong/LinearDQN/"
    model_output: !join_path [*output_path, "saved_weights/"]
    log_path: !join_path [*output_path, "log.txt"]
    plot_output: *output_path
    record_path: !join_path [*output_path, "recordings/"]
    tensorboard: !join_path [*output_path, "tensorboard/"]

model_training:
    load_dir: !join_path [*output_path, "saved_weights/"]
    loss: "double_dqn"
    num_episodes_test: 50
    grad_clip: True
    clip_val: 10
    saving_freq: 250000
    log_freq: 50
    eval_freq: 250000
    record_freq: 250000
    soft_epsilon: 0.05
    compile: False
    compile_mode: "default"

hyper_params:
    nsteps_train: 500000
    batch_size: 32
    buffer_size: 1000000
    target_update_freq: 10000
    gamma: 0.99
    learning_freq: 4
    state_history: 4
    skip_frame: 4
    lr_begin: 0.00008
    lr_end: 0.00005
    lr_nsteps: 500000
    eps_begin: 0.5
    eps_end: 0.1
    eps_nsteps: 1000000
    learning_start: 50000
