# This config run the LinearDQN model on the ALE/Pong-v5 env, but with debug parameter
# i.e. low number of steps and saving, eval, record intervals for debug testing
model: "LinearQN"

env:
    env_name: "ALE/Pong-v5"
    render_train: True
    render_test: True
    overwrite_render: True
    record: True
    max_val: 255.
    render_mode: "rgb_array"

output:
    output_path: &output_path "results/debug_pong/LinearDQN/"
    model_output: !join_path [*output_path, "saved_weights/"]
    log_path: !join_path [*output_path, "log.txt"]
    plot_output: *output_path
    record_path: !join_path [*output_path, "recordings/"]
    tensorboard: !join_path [*output_path, "tensorboard/"]

model_training:
    load_dir: !join_path [*output_path, "saved_weights/"]
    loss: "double_dqn"
    num_episodes_test: 5
    grad_clip: True
    clip_val: 10
    saving_freq: 2500
    log_freq: 50
    eval_freq: 2500
    record_freq: 2500
    soft_epsilon: 0.05
    compile: False
    compile_mode: "default"

hyper_params:
    nsteps_train: 5000
    batch_size: 32
    buffer_size: 1000
    target_update_freq: 100
    gamma: 0.99
    learning_freq: 4
    state_history: 4
    skip_frame: 4
    lr_begin: 0.00008
    lr_end: 0.00005
    lr_nsteps: 5000
    eps_begin: 0.5
    eps_end: 0.1
    eps_nsteps: 1000
    learning_start: 500
    eps: 1e-5
    alpha: 0.6
    beta_begin: 0.4
    beta_end: 1.0
    beta_nsteps: 10000
